import type { Metadata } from "next";
import { Merienda } from "next/font/google";
import "./globals.css";

const merienda = Merienda({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-merienda",
});

export const metadata: Metadata = {
  title: "Luxora-Event Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merienda.className} antialiased`}>{children}</body>
    </html>
  );
}
