import type { Metadata } from "next";
import { Geist, Geist_Mono, Merienda } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merienda = Merienda({
  variable: "--font-merienda",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // Add all desired weights
});

export const metadata: Metadata = {
  title: "Luxora-Event Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merienda.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
