import type { Metadata } from "next";
import { Merienda, Playfair_Display, Lato } from "next/font/google";
import "./globals.css";
import LoadingWrapper from "@/components/LoadingWrapper";  // Corrected the import

const merienda = Merienda({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-merienda",
});

const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-playfair",
});

const lato = Lato({
  weight: ["300", "400", "700", "900"],
  subsets: ["latin"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Luxora-Event Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${merienda.variable} ${playfair.variable} ${lato.variable} antialiased`}
      >
        <LoadingWrapper>{children}</LoadingWrapper>
      </body>
    </html>
  );
}
